[colors.primary]
background = "#000000"

[colors.normal]
green = "#00ff00"
red = "#ff0000"

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font", style = "Bold Italic"}
size = 9.0

[cursor]
style = {shape = "Block", blinking="Always"}

[colors.cursor]
text                  = "#00FF00"
cursor                = "#00FF00"

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
